-- Kura V3's first durable slice: searchable post summaries.
-- search_document is generated so inserts and edits cannot forget to update
-- the full-text index source.
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preview_url TEXT NOT NULL,
    original_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    search_text TEXT NOT NULL DEFAULT '',
    search_document TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple'::regconfig, search_text)
    ) STORED,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS posts_search_document_gin
    ON posts USING GIN (search_document);

CREATE INDEX IF NOT EXISTS posts_visible_created_at_idx
    ON posts (created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
