-- Ordered user collections. Membership only targets visible posts and is
-- unique per collection; deleted posts cannot be added by the API.
CREATE TABLE IF NOT EXISTS collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS collection_posts (
    collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    position BIGINT NOT NULL CHECK (position >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (collection_id, post_id)
);

CREATE INDEX IF NOT EXISTS collection_posts_order_idx
    ON collection_posts (collection_id, position, post_id);
