-- Owner-scoped server saved searches. The actor key is deliberately textual
-- until users and sessions are introduced; current bearer auth supplies the
-- explicit "system" actor and local development supplies "local".
CREATE TABLE IF NOT EXISTS saved_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_actor TEXT NOT NULL CHECK (length(btrim(owner_actor)) BETWEEN 1 AND 120),
    name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    query TEXT NOT NULL CHECK (char_length(query) <= 256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_actor, name)
);

CREATE INDEX IF NOT EXISTS saved_searches_owner_updated_idx
    ON saved_searches (owner_actor, updated_at DESC, id DESC);
