-- Durable identity and capability foundation.
--
-- Idempotent: every statement is safe to re-run, and the lexical runner
-- (scripts/db-migrate.sh applies db/migrations/*.sql in filename order)
-- picks this file up after 007_saved_searches.sql with no script change.
--
-- Additive only: nothing here alters existing tables. In particular,
-- saved_searches.owner_actor stays a free TEXT key so every existing row
-- is preserved byte-for-byte.
--
-- Explicit legacy policy: rows with owner_actor 'local' (local development
-- without KURA_API_TOKEN) and 'system' (requests bearing the deployment
-- KURA_API_TOKEN) remain valid owner keys. They are NOT backfilled to
-- users.id; instead the seed rows below give those two legacy actors a
-- durable identity row each, so future session/grant wiring can reference
-- them without touching historical saved-search rows.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle TEXT NOT NULL UNIQUE CHECK (length(btrim(handle)) BETWEEN 1 AND 120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE CHECK (length(btrim(token_hash)) BETWEEN 1 AND 256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '30 days'),
    revoked_at TIMESTAMPTZ,
    CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS sessions_user_expires_idx
    ON sessions (user_id, expires_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS role_capabilities (
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    capability_id BIGINT NOT NULL REFERENCES capabilities (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, capability_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS resource_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL CHECK (length(btrim(resource_type)) BETWEEN 1 AND 120),
    resource_id TEXT NOT NULL CHECK (length(btrim(resource_id)) BETWEEN 1 AND 256),
    capability_id BIGINT NOT NULL REFERENCES capabilities (id) ON DELETE CASCADE,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, resource_type, resource_id, capability_id)
);

CREATE INDEX IF NOT EXISTS resource_grants_resource_idx
    ON resource_grants (resource_type, resource_id, capability_id);

-- Seed the two legacy actors as durable users. No passwords, OAuth,
-- WebAuthn, or external provider is introduced here.
INSERT INTO users (handle) VALUES ('local'), ('system')
ON CONFLICT (handle) DO NOTHING;

INSERT INTO roles (name) VALUES ('admin'), ('editor'), ('viewer')
ON CONFLICT (name) DO NOTHING;

INSERT INTO capabilities (name) VALUES ('write')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_capabilities (role_id, capability_id)
SELECT r.id, c.id FROM roles r, capabilities c
WHERE r.name IN ('admin', 'editor') AND c.name = 'write'
ON CONFLICT DO NOTHING;

-- Legacy policy in data: the deployment bearer token actor ('system')
-- keeps the write capability through the admin role binding.
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.handle = 'system' AND r.name = 'admin'
ON CONFLICT DO NOTHING;
