-- Bounded moderation slice: post moderation state plus an immutable audit log.
--
-- Idempotent: every statement is safe to re-run, and the lexical runner
-- (scripts/db-migrate.sh applies db/migrations/*.sql in filename order)
-- picks this file up after 008_identity.sql with no script change.
--
-- Additive only: existing rows keep their bytes. The new moderation_state
-- column defaults to 'published', so every pre-moderation post stays visible
-- and deleted_at semantics are unchanged. Capability checks reuse the
-- identity contract from 008_identity.sql; no new capability is introduced.
ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS moderation_state TEXT NOT NULL DEFAULT 'published'
        CHECK (moderation_state IN ('published', 'pending', 'hidden', 'rejected'));

-- Append-only audit of moderation transitions. Immutability is by convention:
-- the API only INSERTs here and never UPDATEs or DELETEs, so history reads
-- as the durable record of who changed what, from which state, and why.
CREATE TABLE IF NOT EXISTS post_moderation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    action TEXT NOT NULL
        CHECK (action IN ('approve', 'pend', 'hide', 'reject')),
    previous_state TEXT NOT NULL
        CHECK (previous_state IN ('published', 'pending', 'hidden', 'rejected')),
    new_state TEXT NOT NULL
        CHECK (new_state IN ('published', 'pending', 'hidden', 'rejected')),
    actor TEXT NOT NULL CHECK (length(btrim(actor)) BETWEEN 1 AND 120),
    reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS post_moderation_actions_post_created_idx
    ON post_moderation_actions (post_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS post_moderation_actions_created_idx
    ON post_moderation_actions (created_at DESC, id DESC);

-- Moderation queue lookups: visible-state filtering ordered newest-first.
CREATE INDEX IF NOT EXISTS posts_moderation_state_idx
    ON posts (moderation_state, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
