-- Durable PostgreSQL job system (unconnected slice).
--
-- Idempotent: every statement is safe to re-run, and the lexical runner
-- (scripts/db-migrate.sh applies db/migrations/*.sql in filename order)
-- picks this file up after 009_moderation.sql with no script change.
--
-- Additive only: nothing here alters existing tables. No worker, upload, or
-- derivative wiring reads this table yet; the status endpoint serves rows
-- once a later slice provides a jobs reader to the HTTP layer.
--
-- Lease model: a claimed row is status 'running' with locked_by holding the
-- worker identity, locked_at recording the claim, and lease_expires_at
-- bounding the lease. Only the lock owner may renew, report progress,
-- succeed, or fail the row. Retries return the row to 'pending' with
-- next_retry_at set from exponential backoff; last_attempt_at records the
-- most recent claim. Terminal states (succeeded, failed, cancelled) set
-- completed_at and clear every lease field.

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK (length(btrim(kind)) BETWEEN 1 AND 120),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    idempotency_key TEXT NOT NULL CHECK (length(btrim(idempotency_key)) BETWEEN 1 AND 256),
    attempts INT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts INT NOT NULL DEFAULT 25 CHECK (max_attempts BETWEEN 1 AND 100),
    next_retry_at TIMESTAMPTZ,
    last_attempt_at TIMESTAMPTZ,
    locked_by TEXT,
    locked_at TIMESTAMPTZ,
    lease_expires_at TIMESTAMPTZ,
    progress INT NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    last_error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    UNIQUE (kind, idempotency_key)
);

-- Claim lookups: oldest due pending row, optionally filtered by kind.
CREATE INDEX IF NOT EXISTS jobs_claim_idx
    ON jobs (created_at ASC, id ASC)
    WHERE status = 'pending';

-- Status polling and kind-scoped inspection.
CREATE INDEX IF NOT EXISTS jobs_status_updated_idx
    ON jobs (status, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS jobs_kind_created_idx
    ON jobs (kind, created_at DESC, id DESC);

-- Lease-expiry sweeps: running rows whose lease lapsed without renewal.
CREATE INDEX IF NOT EXISTS jobs_lease_expiry_idx
    ON jobs (lease_expires_at ASC, id ASC)
    WHERE status = 'running';
